# Generated by Django 3.1.1 on 2020-10-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('coutry', models.CharField(max_length=10, null=True)),
                ('zipcode', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
