# Generated by Django 3.1.1 on 2020-10-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201002_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
