# Generated by Django 3.1.1 on 2020-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_donation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
