# Generated by Django 3.1.1 on 2020-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_donation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='county',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='coutry',
            field=models.CharField(max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='state',
            field=models.CharField(max_length=2, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name=''),
        ),
    ]
