# Generated by Django 3.1.1 on 2020-10-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20201003_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.IntegerField(max_length=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.IntegerField(max_length=15, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zipcode',
            field=models.IntegerField(max_length=10, null=True, verbose_name=''),
        ),
    ]
