# Generated by Django 3.1.1 on 2020-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20201003_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cardnum',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(max_length=20, null=True, verbose_name=''),
        ),
    ]
